title: 'Musical-World: Informationen zum Thema Musicals'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6875
  brandStrength: 0.3125
  rhythmicContrast: 1
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#af870e'
    - '#981205'
    - '#26425a'
  lightness: 0.6875
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Musical-World
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.40501
layout_spectrum: 0.2446809
